version: "3"

services:
  my-mining-stats:
    image: node:14-alpine
    container_name: my-mining-stats
    working_dir: /app
    volumes:
      - "./:/app"
    environment:
      DEBUG: "false"
    restart: always
    command: sh -c "npm install && npm start"
